
package com.javadb.ws.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ExampleServiceService", targetNamespace = "http://example.ws.javadb.com/", wsdlLocation = "http://localhost:8080/example/exampleService?wsdl")
public class ExampleServiceService
    extends Service
{

    private final static URL EXAMPLESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.javadb.ws.example.client.ExampleServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.javadb.ws.example.client.ExampleServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/example/exampleService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/example/exampleService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EXAMPLESERVICESERVICE_WSDL_LOCATION = url;
    }

    public ExampleServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExampleServiceService() {
        super(EXAMPLESERVICESERVICE_WSDL_LOCATION, new QName("http://example.ws.javadb.com/", "ExampleServiceService"));
    }

    /**
     * 
     * @return
     *     returns ExampleService
     */
    @WebEndpoint(name = "ExampleServicePort")
    public ExampleService getExampleServicePort() {
        return super.getPort(new QName("http://example.ws.javadb.com/", "ExampleServicePort"), ExampleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExampleService
     */
    @WebEndpoint(name = "ExampleServicePort")
    public ExampleService getExampleServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.ws.javadb.com/", "ExampleServicePort"), ExampleService.class, features);
    }

}
